# Generated by Django 4.0.2 on 2022-02-23 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=100000)),
                ('create_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
