# Generated by Django 3.2.12 on 2022-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='age',
        ),
        migrations.AddField(
            model_name='country',
            name='place',
            field=models.CharField(default='Europe', max_length=30),
        ),
    ]
